import { ContentItem, Fields } from 'kentico-cloud-delivery-typescript-sdk';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class Product extends ContentItem {
    public nazov: Fields.TextField;
    public hmotnost: Fields.TextField;
    public vyrobca: Fields.TaxonomyField;
    public kategoria: Fields.TaxonomyField;
    public krajinaPovodu: Fields.TaxonomyField;
    public popis: Fields.TextField;
    public foto: Fields.AssetsField;

    constructor(){
        super({
            propertyResolver: ((fieldName: string) => {

                if (fieldName === 'krajina_povodu'){
                    return 'krajinaPovodu';
                }

                return fieldName;
            })
        })
    }
}
